<script>
    $(document).ready(function () {

        var datamk = [];

        $('.drag').draggable({
            appendTo: 'body',
            helper: 'clone',
            stack: 'div',
        });

        $('#dropzone').droppable({
            activeClass: 'active',
            hoverClass: 'hover',
            accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
            drop: function (e, ui) {
                var $el = $('<li class="list-group-item drop-item">' + ui.draggable.text() +
                    '</li>'
                );


                $el.append(
                    '<input type="hidden" name="mklist[]" value="' + ui.draggable.attr(
                        'data-id') + '">');

                $el.append($(
                    '<button type="button" class="btn btn-danger btn-sm remove">hapus</button>'
                ).click(function () {
                    $(this).parent().detach();

                    if (datamk.length > 0) {

                        for (var i = 0; i < datamk.length; i++) {
                            if (datamk[i].trim() == ui.draggable.attr('data-id')
                                .trim()) {
                                datamk.splice(i, 1);
                            }
                        }
                    }
                    if (datamk.length == 0) {

                        $('.dz-message').show();
                    }

                }));

                var isAvail = false;

                if (datamk.length > 0) {
                    for (var i = 0; i < datamk.length; i++) {
                        if (datamk[i].trim() == ui.draggable.attr('data-id').trim()) {
                            // console.log(datamk);
                            isAvail = true;

                        }
                    }
                    if (!isAvail) {

                        $(this).append($el);
                        datamk.push(ui.draggable.attr('data-id').trim());
                    }
                } else {
                    datamk.push(ui.draggable.attr('data-id').trim());
                    $(this).append($el);
                    $('.dz-message').hide();
                }


            },


        }).sortable({
            items: '.drop-item',
            sort: function () {
                // gets added unintentionally by droppable interacting with sortable
                // using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
                $(this).removeClass("active");
            }
        });
    })

</script>
