@extends('layouts.main')
@section('rps', 'active')
@section('step1', 'active')
@section('content')

<section class="section">

    <div class="section-body">
        <h2 class="section-title">Plotting Rumpun Mata Kuliah</h2>
        <div class="row">
            <div class="col-lg-6">
                <div class="card">
                    <div class="card-header">
                        <h4>Daftar Mata Kuliah</h4>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped" id="table">
                            <thead>
                                <tr>
                                    <th>Nama Mata Kuliah</th>
                                </tr>
                            </thead>
                            <tbody id="modules">
                                <tr>
                                    <td>
                                        <div class="drag" data-id="1">
                                            <span>Sistem Pendukung Keputusan</span>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="drag" data-id="2">
                                            <span>Teknologi Big Data</span>
                                        </div>
                                    </td>
                                </tr>
                                <tr>
                                    <td>
                                        <div class="drag" data-id="3">
                                            <span>Kualitas Data</span>
                                        </div>
                                    </td>
                                </tr>

                            </tbody>
                        </table>

                    </div>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="card carddrop">
                    <div class="card-header">
                        <h4>Rumpun Mata Kuliah</h4>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Nama Rumpun Mata Kuliah</label>
                            <input type="text" class="form-control">
                        </div>
                        <div class="form-group">
                            <label>Ketua Rumpun</label>
                            <select class="form-control select2">
                                <option value="" selected disabled>Pilih Dosen</option>
                                <option>Vivine Nurcahyawati</option>
                                <option>Tutut Wurijanto</option>
                                <option>Norma Ningsih</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="">Daftar Mata Kuliah</label>
                            <ul class="list-group" id="dropzone">
                                <div class="dz-message"><span>Drag Nama Mata Kuliahnya kesini</span></div>
                            </ul>
                        </div>
                        <div class="form-group">
                            <button type="button" class="btn btn-primary">Simpan</button>
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>


</section>
@endsection
@push('script')
<script>
    $(document).ready(function () {

        var datamk = [];

        $('.drag').draggable({
            appendTo: 'body',
            helper: 'clone',
            stack: 'div',
        });

        $('#dropzone').droppable({
            activeClass: 'active',
            hoverClass: 'hover',
            accept: ":not(.ui-sortable-helper)", // Reject clones generated by sortable
            drop: function (e, ui) {
                var $el = $('<li class="list-group-item drop-item">' + ui.draggable.text() +
                    '</li>'
                );

                $el.append($(
                    '<button type="button" class="btn btn-danger btn-sm remove">hapus</button>'
                ).click(function () {
                    $(this).parent().detach();

                    if (datamk.length > 0) {

                        for (var i = 0; i < datamk.length; i++) {
                            if (datamk[i].trim() == ui.draggable.text().trim()) {
                                datamk.splice(i, 1);
                            }
                        }
                    }
                    if (datamk.length == 0) {

                        $('.dz-message').show();
                    }

                }));

                var isAvail = false;

                if (datamk.length > 0) {
                    for (var i = 0; i < datamk.length; i++) {
                        if (datamk[i].trim() == ui.draggable.text().trim()) {
                            // console.log(datamk);
                            isAvail = true;

                        }
                    }
                    if (!isAvail) {

                        $(this).append($el);
                        datamk.push(ui.draggable.text().trim());
                    }
                } else {
                    datamk.push(ui.draggable.text().trim());
                    $(this).append($el);
                    $('.dz-message').hide();
                }


            },


        }).sortable({
            items: '.drop-item',
            sort: function () {
                // gets added unintentionally by droppable interacting with sortable
                // using connectWithSortable fixes this, but doesn't allow you to customize active/hoverClass options
                $(this).removeClass("active");
            }
        });
    })

</script>
@endpush
